name: continuous-integration-foo

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on:  ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build with Gradle!
              working-directory: .
              run: ./gradlew build -x test

            - name: Run tests
              working-directory: .
              run: ./gradlew test

    system-test:
        runs-on: ubuntu-latest
        needs: build-and-test # make sure unit testing is run first
        steps:
            - uses: actions/checkout@v1

            - name: Build the docker-compose stack
              run: docker-compose up -d --build

            - uses: actions/setup-python@v1
              with:
                python-version: '3.8.0' # Version range or exact version of a Python version to use, using SemVer's version range syntax

            - name: Install requests and pytest
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -U requests
                  pip3 install -U pytest

            - name: Run pytest
              run: pytest

            - name: Purge docker-compose
              run: docker-compose down
